index.js
=> more emotes

commands/archive.js
condense multi-line variable assignments
remove set position workaround
defer reply (due to potential ratelimiting)
=> improve archive

commands/alumnize.js, commands/archive.js, commands/assign.js, commands/create.js, commands/demote.js, commands/invite.js, commands/lock.js, commands/open.js, commands/react.js, commands/reply.js, commands/send.js, commands/timeout.js, commands/unlock.js, index.js, registerCommands.js, utils.js
Mostly tested but full testing is blocked by #23 (so many hardcoded constants)
=> Switch from wokcommands

package-lock.json, package.json
=> Add node-fetch types

src/index.ts, src/utils.ts
=> fix: #update-role doesn't work

src/utils.ts
sorrow fills the day as i develop imposter syndrome
=> fix compile error (add comma)

src/commands/alumnize.ts, src/index.ts
If a role is being adding and another is being removed, do the addition first
=> Prioritize adding role in role swap

.gitignore, docker-compose.yml, src/command.ts, src/commands/reroll.ts, src/config.ts, src/configTypes.ts, src/db.ts, src/index.ts
- **feat: authorize certain roles to use commands**
- **fix: db resetting on container update**
=> fix db reset on deployment

docker-compose.yml
- **feat: authorize certain roles to use commands**
- **fix: db resetting on container update**
- **fix: duplicate environment variables in docker-compose.yml**
=> fix duplicate environment variables

src/commands/send.ts
- **feat: only redeploy commands when data is changed**
- **feat: use message link for send command**
=> message link in send command

.github/workflows/docker.yaml
manually trigger image build -> manually restart zombbblob
=> feat: manual zombbblob restart

.gitignore, src/commands/add-word.ts, src/commands/end-zombbblob.ts, src/commands/get-all-words.ts, src/commands/infected-word.ts, src/commands/load-zip-games.ts, src/commands/loadwordlist.ts, src/commands/remove-word.ts, src/commands/reroll.ts, src/commands/start-zombbblob.ts, src/commands/zip-average.ts, src/config.ts, src/configTypes.ts, src/games/zipgame.ts, src/games/zipgamedb.ts, src/games/zombbblobdb.ts, src/games/zombiegame.ts, src/index.ts, tsconfig.json
* /zip-average: average stats of Zip game
* /zip-load-historic-submissions: load submissions made before tracking
=> feat: LinkedIn Zip stats

src/commands/zip-average.ts, src/commands/zip-load-historic-submissions.ts, src/games/zipgame.ts, src/games/zipgamedb.ts
If user's Zip average improves the current average, tell them!
=> Reply on improved Zip average

src/commands/zip-get-latest-submission.ts, src/games/zipgame.ts, src/games/zipgamedb.ts
- **refactor: match Zip Result interface to db Scheme**
- **feat: command to user's get latest Zip submission**
=> zip get latest submission

src/commands/zip-get-latest-submission.ts, src/games/zipgamedb.ts
- **fix: remove hard-coded constants**
- **chore: remove unused import**
- **fix: zip-get-latest-submission returns the *latest* submission**
=> fix zip get submission

src/commands/zip-average.ts, src/commands/zip-load-historic-submissions.ts, src/games/zipgame.ts, src/games/zipgamedb.ts
- **fix: don't load historic submissions with invalid game numbers**
- **feat: support non-logged in zip submissions**
=> support guest zip submissions

src/games/zipgame.ts
- **feat: extensible zip message parsing**
- **feat: support chinese (traditional) zip submissions**
=> extensible zip submission formats

src/games/zipgame.ts
=> docs: explain Zip regex

src/commands/zip-average.ts, src/games/zipgame.ts, src/games/zipgamedb.ts
credit to @guanlin-li for the response design
=> feat: weekly zip average and new average response design

package-lock.json, package.json, src/commands/zip-average.ts, src/games/zipgame.ts, src/games/zipgamedb.ts
was still in my node_modules from a different unpushed branch
=> fix: add missing luxon dependency
